# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
archives:
  - name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
nfpms:
  - id: github.com/joshuar/cf-ddns
    package_name: cf-ddns
    vendor: github.com/joshuar
    homepage: https://github.com/joshuar/cf-ddns
    maintainer: Josh Rich <joshua.rich@gmail.com>
    description: A Dynamic DNS client for Cloudflare.
    license: MIT
    release: "1"

    formats:
      - deb
      - rpm

    # Section.
    section: default

    # Priority.
    priority: extra

    # Contents to add to the package.
    # GoReleaser will automatically add the binaries.
    contents:
      # Basic file that applies to all packagers
      - src: configs/cf-ddns.yml
        dst: /etc/cf-ddns/cf-ddns.yml
        type: "config|noreplace"

      # Simple config file
      - src: systemd/cf-ddns.service
        dst: /usr/lib/systemd/system/cf-ddns.service
        type: config

    scripts:
      # preinstall: "scripts/preinstall.sh"
      postinstall: "scripts/postinstall.sh"
      # preremove: "scripts/preremove.sh"
      # postremove: "scripts/postremove.sh"